name: CI

on:
  push:
    branches: [ git_hub_actions, main ]
  pull_request:
    branches: [ git_hub_actions, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    - name: Install browsers
      run: |
        python -m playwright install

    - name: Start app
      run: nohup uvicorn app.main:app --host 0.0.0.0 --port 8181 &
    - name: Wait for server
      run: sleep 5

    - name: Run pytest
      run: |
        if [ -d tests ]; then
          python -m pytest tests --maxfail=1 --disable-warnings -v
        else
          echo "Skip test"
        fi